apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "sccsos" }}
  labels:
    app.kubernetes.io/name: sccsos
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
