apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sccsos-data
  namespace: sccsos
  labels:
    app.kubernetes.io/name: sccsos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sccsos-logs
  namespace: sccsos
  labels:
    app.kubernetes.io/name: sccsos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
